name: Android CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Setup Java 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: '17'
        check-latest: false
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@460a3ca55fc5d559238a0efc7fa9f7465df8585d
    - name: Build with Gradle
      run: ./gradlew build
    - name: Bundle (Debug)
      run: ./gradlew bundleDebug
    - uses: actions/upload-artifact@v4.3.2
      with:
        name: Package
        path: ./build
