name: Android CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup Java 17
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'adopt'
        java-version: '17'
        check-latest: false
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@27152f6fa06a6b8062ef7195c795692e51fc2c81
    - name: Build with Gradle
      run: ./gradlew build
    - name: Bundle (Debug)
      run: ./gradlew bundleDebug
    - uses: actions/upload-artifact@v4.3.1
      with:
        name: Package
        path: ./build
