name: Android CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - name: Setup Java 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: '17'
        check-latest: false
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@9ba54b687bf0f59b62abbf91e0d60de082e8ebc4
    - name: Build with Gradle
      run: ./gradlew build
    - name: Bundle (Debug)
      run: ./gradlew bundleDebug
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: Package
        path: ./build
