name: Android CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Setup Java 17
      uses: actions/setup-java@v3.3.0
      with:
        distribution: 'adopt'
        java-version: '17'
        check-latest: false
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b
    - name: Build with Gradle
      run: ./gradlew build
    - name: Bundle (Debug)
      run: ./gradlew bundleDebug
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: Package
        path: ./build
